### ISSUE TITLE
Tudo em um único XAML

### ISSUE THREAD

**Issue by mapsouza** [MonkeyNights/juntos-shell-now#2]
Pelo que eu entendi, toda a navegação do APP vai ser definida em um único XAML. É isso mesmo produção?
Fiquei confuso no caso de navegações mais profundas... tipo uma página de detalhes dos detalhes...

**Comment by RonildoSouza** [comment]
Acho que este link aqui responde a sua duvida @mapsouza e deve dar uma iluminada nas ideias..rs

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/navigation

**Comment by angelobelchior** [comment]
> Pelo que eu entendi, toda a navegação do APP vai ser definida em um único XAML. É isso mesmo produção?
> Fiquei confuso no caso de navegações mais profundas... tipo uma página de detalhes dos detalhes...

Na verdade a ideia é ter a estrutura da Shell num arquivo só. A navegação em si acaba ficando da mesma forma que antes com algumas melhorias em relação aos parâmetros etc. Estamos estudando tudo isso pra entender melhor :)
